name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Publishing version (tag name)
      dry-run:
        description: 'Run in dry-run mode (no actual publish)'
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - name: Checkout Quill repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.version }}

      - name: Build
        uses: ./.github/actions/quill/steps/build

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'

      - name: Pack
        run: |
          package_tgz=$(pnpm pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')
          echo "PACKAGE_TGZ=$package_tgz" >> "$GITHUB_ENV"

      - name: Publish to NPM
        run: pnpm publish "$PACKAGE_TGZ" --provenance --no-git-checks ${{ inputs['dry-run'] && '--dry-run' || '' }}

      - name: Setup NPM tags
        if: ${{ !inputs['dry-run'] }}
        run: |
          npm dist-tag add devextreme-quill@${{ inputs.version }} 24_1
          npm dist-tag add devextreme-quill@${{ inputs.version }} 24_2
          npm dist-tag add devextreme-quill@${{ inputs.version }} 25_1
